[build]
  publish = "."
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/auth.html"
  to = "/auth.html"
  status = 200

[[redirects]]
  from = "/create/*"
  to = "/create/index.html"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/user/*"
  to = "/user-template.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "."
